begin;
create function pg_temp.check_ok(ok boolean,message text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception '%',message;end if; end $$;
set local role authenticated;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
do $$
declare sid uuid:='30000000-0000-4000-8000-000000000003'; cid uuid:=gen_random_uuid(); core jsonb; rev bigint; old jsonb; failed boolean; result jsonb; unchanged_tid tid;
 part0 jsonb:='[{"id":"upload-horse","kind":"horse","name":"母と仔"}]';
 part1 jsonb:='[{"id":"upload-scene","kind":"scene"}]';
begin
 old=public.load_owner_save(); core=old#>'{state,core}'; rev=(old->>'revision')::bigint;
 perform public.begin_owner_upload(sid,cid,rev,core,true,2);
 perform public.append_owner_upload(cid,1,part1);
 perform public.append_owner_upload(cid,1,part1);
 perform pg_temp.check_ok(public.load_owner_save()=old,'partial upload never changes the save');
 failed=false;begin perform public.finish_owner_upload(cid);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed,'incomplete upload rejected');
 failed=false;begin perform public.append_owner_upload(cid,1,part0);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed,'changed chunk rejected');
 failed=false;begin perform public.begin_owner_upload(sid,cid,rev,core,true,3);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed,'changed metadata rejected');
 perform public.append_owner_upload(cid,0,part0);
 result=public.finish_owner_upload(cid);
 perform pg_temp.check_ok((result->>'revision')::bigint=rev+1,'complete upload commits once');
 perform pg_temp.check_ok((select state from public.owner_checkpoints where revision=rev)=old->'state','staged restore preserves previous checkpoint');
 perform pg_temp.check_ok((select count(*) from public.owner_entities)=2,'restore replaces the entire entity set');
 -- Simulate a lost final response: re-upload with exactly the same command and bytes.
 perform public.begin_owner_upload(sid,cid,rev,core,true,2);
 perform public.append_owner_upload(cid,0,part0);
 perform public.append_owner_upload(cid,1,part1);
 result=public.finish_owner_upload(cid);
 perform pg_temp.check_ok((result->>'revision')::bigint=rev+1,'lost final response remains idempotent');
 perform public.begin_owner_upload(sid,cid,rev,core,true,2);
 perform public.append_owner_upload(cid,0,part0||'[{"id":"changed","kind":"horse"}]'::jsonb);
 perform public.append_owner_upload(cid,1,part1);
 failed=false;begin perform public.finish_owner_upload(cid);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed,'reusing committed upload id with different entities rejected');
 old=public.load_owner_save();rev=(old->>'revision')::bigint;cid=gen_random_uuid();
 perform public.begin_owner_upload(sid,cid,rev,core,true,1);
 perform public.append_owner_upload(cid,0,'[{"id":"valid","kind":"horse"},{"id":"bad","kind":"unsupported"}]');
 failed=false;begin perform public.finish_owner_upload(cid);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed and public.load_owner_save()=old,'invalid staged replacement is atomic');
 cid=gen_random_uuid();perform public.begin_owner_upload(sid,cid,rev,core,true,1);
 perform public.append_owner_upload(cid,0,part0);
 perform public.commit_owner_save(sid,gen_random_uuid(),rev,core,'[]',false);
 failed=false;begin perform public.finish_owner_upload(cid);exception when sqlstate 'PT409' then failed=true;end;
 perform pg_temp.check_ok(failed,'concurrent ordinary save wins CAS over stale upload');
 failed=false;begin perform public.begin_owner_upload(sid,gen_random_uuid(),rev,core,true,33);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed,'upload count bounded');
 failed=false;begin perform public.append_owner_upload(cid,0,jsonb_build_array(jsonb_build_object('padding',repeat('x',2000001))));exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed,'individual chunk size bounded');
 -- A pending legacy direct commit can be retried through staging after an app update.
 old=public.load_owner_save();
 perform public.begin_owner_upload(sid,'40000000-0000-4000-8000-000000000004',0,core||'{"engineVersion":"owner-p1","rulesetVersion":"foundation-2026"}'::jsonb,false,1);
 perform public.append_owner_upload('40000000-0000-4000-8000-000000000004',0,'[{"id":"horse-1","kind":"horse","name":"before"}]');
 perform public.finish_owner_upload('40000000-0000-4000-8000-000000000004');
 perform pg_temp.check_ok(public.load_owner_save()=old,'legacy direct command replay through staging preserves the current save');
 rev=(public.load_owner_save()->>'revision')::bigint;
 perform public.commit_owner_save(sid,gen_random_uuid(),rev,core,'[{"id":"remove-me","kind":"event"}]',false);
 old=public.load_owner_save();rev=(old->>'revision')::bigint;
 select ctid into unchanged_tid from public.owner_entities where save_id=sid and id='upload-scene';
 cid=gen_random_uuid();perform public.begin_owner_upload(sid,cid,rev,core,true,1);
 perform public.append_owner_upload(cid,0,'[{"id":"upload-horse","kind":"horse","name":"next"},{"id":"upload-scene","kind":"scene"},{"id":"new-horse","kind":"horse"}]');
 perform public.finish_owner_upload(cid);
 perform pg_temp.check_ok((select count(*) from public.owner_entities)=3 and not exists(select 1 from public.owner_entities where id='remove-me'),'replacement deletes omitted IDs and adds new IDs');
 perform pg_temp.check_ok((select body->>'name' from public.owner_entities where id='upload-horse')='next','replacement updates changed content');
 perform pg_temp.check_ok((select ctid from public.owner_entities where id='upload-scene')=unchanged_tid,'unchanged entity is retained without a rewrite');
 perform pg_temp.check_ok((select state from public.owner_checkpoints where revision=rev)=old->'state','optimized snapshot preserves exact old state');
 failed=false;begin perform * from public.owner_uploads;exception when insufficient_privilege then failed=true;end;
 perform pg_temp.check_ok(failed,'direct staging read denied');
end;
$$;
do $$
declare sid uuid:='30000000-0000-4000-8000-000000000003'; cid uuid; old jsonb; core jsonb; rev bigint; failed boolean;
 a jsonb:=jsonb_build_array(jsonb_build_object('id','escaped-history','kind','event','text',E'母と仔 [a, b] "引用"\n改行\\末尾','nested',jsonb_build_array(null,true,1.25)));
 b jsonb:='[{"id":"second-history","kind":"event","text":"[,]"}]';
begin
 old=public.load_owner_save();core=old#>'{state,core}';rev=(old->>'revision')::bigint;cid=gen_random_uuid();
 perform public.commit_owner_save(sid,cid,rev,core,a||b,false);
 perform public.begin_owner_upload(sid,cid,rev,core,false,4);
 perform public.append_owner_upload(cid,3,b);perform public.append_owner_upload(cid,0,'[]');
 perform public.append_owner_upload(cid,2,'[]');perform public.append_owner_upload(cid,1,a);
 perform public.finish_owner_upload(cid);
 perform pg_temp.check_ok((public.load_owner_save()->>'revision')::bigint=rev+1,'direct to staged replay hash matches with empty chunks, escapes, Unicode and nested values');
 rev=rev+1;cid=gen_random_uuid();
 perform public.begin_owner_upload(sid,cid,rev,core,false,2);
 perform public.append_owner_upload(cid,0,a);perform public.append_owner_upload(cid,1,b);
 perform public.finish_owner_upload(cid);
 perform public.commit_owner_save(sid,cid,rev,core,a||b,false);
 perform pg_temp.check_ok((public.load_owner_save()->>'revision')::bigint=rev+1,'staged to direct replay hash matches');
 old=public.load_owner_save();rev=rev+1;cid=gen_random_uuid();
 perform public.begin_owner_upload(sid,cid,rev,core,true,2);
 perform public.append_owner_upload(cid,0,a);perform public.append_owner_upload(cid,1,a);
 failed=false;begin perform public.finish_owner_upload(cid);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed and public.load_owner_save()=old,'duplicate IDs across chunks rejected atomically');
 cid=gen_random_uuid();perform public.begin_owner_upload(sid,cid,rev,core,true,2);
 perform public.append_owner_upload(cid,0,a);perform public.append_owner_upload(cid,1,'[{"id":"bad-later","kind":"unknown"}]');
 failed=false;begin perform public.finish_owner_upload(cid);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed and public.load_owner_save()=old,'invalid later chunk rejected before any checkpoint or write');
 cid=gen_random_uuid();perform public.begin_owner_upload(sid,cid,rev,core||'{"rulesetVersion":"unknown"}'::jsonb,true,1);
 perform public.append_owner_upload(cid,0,a);
 failed=false;begin perform public.finish_owner_upload(cid);exception when sqlstate '22023' then failed=true;end;
 perform pg_temp.check_ok(failed and public.load_owner_save()=old,'unsupported staged core rejected atomically');
end $$;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000002',true);
do $$declare failed boolean=false;begin
 begin perform public.begin_owner_upload('30000000-0000-4000-8000-000000000003',gen_random_uuid(),0,'{"saveId":"30000000-0000-4000-8000-000000000003"}',true,1);exception when insufficient_privilege then failed=true;end;
 perform pg_temp.check_ok(failed,'other owner cannot stage into this save');
 failed=false;begin perform public.finish_owner_upload(gen_random_uuid());exception when sqlstate 'PT409' then failed=true;end;
 perform pg_temp.check_ok(failed,'other owner cannot finalize an upload');
end $$;
set local role anon;
do $$declare failed boolean=false;begin
 begin perform public.finish_owner_upload(gen_random_uuid());exception when insufficient_privilege then failed=true;end;
 perform pg_temp.check_ok(failed,'anonymous staging RPC denied');
end $$;
reset role;
delete from public.owner_uploads;
commit;
